server:
  port: ${port:8480}
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  hateoas:
    use-hal-as-default-json-media-type: false
security:
  basic:
    enabled: false

api:
  docs:
    title: Transaction service REST API
    description: Documentation de l'API REST exposée par le service de gestion des transactions
    version: 1.0
    termsOfServiceUrl: https://github.com/rjansem/spring-cloud-ms-training
    license: © 2017 rjansem
    licenseUrl: https://github.com

business:
  operations:
    defaultPageSize: 20

hystrix:
  threadpool:
    efs-service:
      coreSize: 32
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 1000
  command:
    efs-service:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 2000
logging:
  file: c:/tmp/transaction-service.log
  level:
    com.github.rjansem.microservices.training: TRACE
    org.springframework: WARN
    com.netflix: WARN
    root: ERROR
  pattern:
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] %level %logger{36}@%method:%line - %msg%n'

redis:
  caches:
    - name: ordresCache
      expiry: 300
    - name: transactionsCache
      expiry: 300

---
spring:
  profiles: dev
security:
  oauth2:
    client:
      client-id: efs
      client-secret: efssecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnXAnwPOR4iFT2Sff8HvNl3Hu8w7+ffk/Fem6SyUeEI0J2URaciZO394y0dCPG6+W6yJQ867Ilus4EnHgz4+IHmOf0hX9Jf6ITPGaCrW+UCQAm9ELrLfJXiZPN2hraKAn6lErDoDsVTcO1NHfU3TnkpgMDaz6IrUUTU9tz0LtJCvTT+ic5TRataX3VxQpT0klos0vJpvrn0wgY5F8qLmBkW6QGVnWD08hxQfMc0IcINQqLyI9IOcqIPIPA3ikNqRKoDxTl1moJpI+oywwr8eMlARdrR9mD3HzHAfio5+pnNSIC9SmEdhXeHIuSPtYTiVwwqhk8+E+tOQaCa59YBN/DwIDAQAB
          -----END PUBLIC KEY-----

