filebeat.prospectors:
- input_type: log
  paths:
    - c:/tmp/account-service.log
    - c:/tmp/profile-service.log
    - c:/tmp/transaction-service.log

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["127.0.0.1:5044"]