heartbeat.monitors:
- type: http
  schedule: '@every 10s'
  urls: ["http://localhost:8888/health", "http://localhost:8761/health", "http://localhost:9080/health", "http://localhost:8280/health", "http://localhost:8380/health", "http://localhost:8480/health"]
  ssl:
    verification_mode: none
check.response:
  status: 200
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["127.0.0.1:5044"]