spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
      allowOverride: true
      overrideNone: false
      overrideSystemProperties: false
  profiles:
     active: native
server:
  port: ${port:8888}
logging:
  path: c:/tmp
  level:
    com.github.rjansem.microservices.training: TRACE
